version: '3.8'

services:
  db:
    image: postgres:13
    container_name: gateau_db
    environment:
      POSTGRES_DB: orderer_local
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"